export const periodicTable = {
  1: { name: 'Hydrogen', symbol: 'H', group: '1', period: '1', category: 'Nonmetals' },
  2: { name: 'Helium', symbol: 'He', group: '18', period: '1', category: 'Noble Gas' },
  3: { name: 'Lithium', symbol: 'Li', group: '1', period: '2', category: 'Alkali Metals' },
  4: { name: 'Beryllium', symbol: 'Be', group: '2', period: '2', category: 'Alkaline Earth Metals' },
  5: { name: 'Boron', symbol: 'B', group: '13', period: '2', category: 'Metalloids' },
  6: { name: 'Carbon', symbol: 'C', group: '14', period: '2', category: 'Nonmetals' },
  7: { name: 'Nitrogen', symbol: 'N', group: '15', period: '2', category: 'Nonmetals' },
  8: { name: 'Oxygen', symbol: 'O', group: '16', period: '2', category: 'Nonmetals' },
  9: { name: 'Fluorine', symbol: 'F', group: '17', period: '2', category: 'Halogen' },
 10: { name: 'Neon', symbol: 'Ne', group: '18', period: '2', category: 'Noble Gas' },
 11: { name: 'Sodium', symbol: 'Na', group: '1', period: '3', category: 'Alkali Metals' },
 12: { name: 'Magnesium', symbol: 'Mg', group: '2', period: '3', category: 'Alkaline Earth Metals' },
 13: { name: 'Aluminum', symbol: 'Al', group: '13', period: '3', category: 'Metals' },
 14: { name: 'Silicon', symbol: 'Si', group: '14', period: '3', category: 'Metalloids' },
 15: { name: 'Phosphorus', symbol: 'P', group: '15', period: '3', category: 'Nonmetals' },
 16: { name: 'Sulfur', symbol: 'S', group: '16', period: '3', category: 'Nonmetals' },
 17: { name: 'Chlorine', symbol: 'Cl', group: '17', period: '3', category: 'Halogen' },
 18: { name: 'Argon', symbol: 'Ar', group: '18', period: '3', category: 'Noble Gas' },
 19: { name: 'Potassium', symbol: 'K', group: '1', period: '4', category: 'Alkali Metals' },
 20: { name: 'Calcium', symbol: 'Ca', group: '2', period: '4', category: 'Alkaline Earth Metals' },
 21: { name: 'Scandium', symbol: 'Sc', group: '3', period: '4', category: 'Transition Metal' },
 22: { name: 'Titanium', symbol: 'Ti', group: '4', period: '4', category: 'Transition Metal' },
 23: { name: 'Vanadium', symbol: 'V', group: '5', period: '4', category: 'Transition Metal' },
 24: { name: 'Chromium', symbol: 'Cr', group: '6', period: '4', category: 'Transition Metal' },
 25: { name: 'Manganese', symbol: 'Mn', group: '7', period: '4', category: 'Transition Metal' },
 26: { name: 'Iron', symbol: 'Fe', group: '8', period: '4', category: 'Transition Metal' },
 27: { name: 'Cobalt', symbol: 'Co', group: '9', period: '4', category: 'Transition Metal' },
 28: { name: 'Nickel', symbol: 'Ni', group: '10', period: '4', category: 'Transition Metal' },
 29: { name: 'Copper', symbol: 'Cu', group: '11', period: '4', category: 'Transition Metal' },
 30: { name: 'Zinc', symbol: 'Zn', group: '12', period: '4', category: 'Transition Metal' },
 31: { name: 'Gallium', symbol: 'Ga', group: '13', period: '4', category: 'Metals' },
 32: { name: 'Germanium', symbol: 'Ge', group: '14', period: '4', category: 'Metalloids' },
 33: { name: 'Arsenic', symbol: 'As', group: '15', period: '4', category: 'Metalloids' },
 34: { name: 'Selenium', symbol: 'Se', group: '16', period: '4', category: 'Nonmetals' },
 35: { name: 'Bromine', symbol: 'Br', group: '17', period: '4', category: 'Halogen' },
 36: { name: 'Krypton', symbol: 'Kr', group: '18', period: '4', category: 'Noble Gas' },
 37: { name: 'Rubidium', symbol: 'Rb', group: '1', period: '5', category: 'Alkali Metals' },
 38: { name: 'Strontium', symbol: 'Sr', group: '2', period: '5', category: 'Alkaline Earth Metals' },
 39: { name: 'Yttrium', symbol: 'Y', group: '3', period: '5', category: 'Transition Metal' },
 40: { name: 'Zirconium', symbol: 'Zr', group: '4', period: '5', category: 'Transition Metal' },
 41: { name: 'Niobium', symbol: 'Nb', group: '5', period: '5', category: 'Transition Metal' },
 42: { name: 'Molybdenum', symbol: 'Mo', group: '6', period: '5', category: 'Transition Metal' },
 43: { name: 'Technetium', symbol: 'Tc', group: '7', period: '5', category: 'Transition Metal' },
 44: { name: 'Ruthenium', symbol: 'Ru', group: '8', period: '5', category: 'Transition Metal' },
 45: { name: 'Rhodium', symbol: 'Rh', group: '9', period: '5', category: 'Transition Metal' },
 46: { name: 'Palladium', symbol: 'Pd', group: '10', period: '5', category: 'Transition Metal' },
 47: { name: 'Silver', symbol: 'Ag', group: '11', period: '5', category: 'Transition Metal' },
 48: { name: 'Cadmium', symbol: 'Cd', group: '12', period: '5', category: 'Transition Metal' },
 49: { name: 'Indium', symbol: 'In', group: '13', period: '5', category: 'Metals' },
 50: { name: 'Tin', symbol: 'Sn', group: '14', period: '5', category: 'Metals' },
 51: { name: 'Antimony', symbol: 'Sb', group: '15', period: '5', category: 'Metalloids' },
 52: { name: 'Tellurium', symbol: 'Te', group: '16', period: '5', category: 'Metalloids' },
 53: { name: 'Iodine', symbol: 'I', group: '17', period: '5', category: 'Halogen' },
 54: { name: 'Xenon', symbol: 'Xe', group: '18', period: '5', category: 'Noble Gas' },
 55: { name: 'Cesium', symbol: 'Cs', group: '1', period: '6', category: 'Alkali Metals' },
 56: { name: 'Barium', symbol: 'Ba', group: '2', period: '6', category: 'Alkaline Earth Metals' },
 57: { name: 'Lanthanum', symbol: 'La', group: '3', period: '6', category: 'Lanthanide' },
 58: { name: 'Cerium', symbol: 'Ce', group: '-', period: '6', category: 'Lanthanide' },
 59: { name: 'Praseodymium', symbol: 'Pr', group: '-', period: '6', category: 'Lanthanide' },
 60: { name: 'Neodymium', symbol: 'Nd', group: '-', period: '6', category: 'Lanthanide' },
 61: { name: 'Promethium', symbol: 'Pm', group: '-', period: '6', category: 'Lanthanide' },
 62: { name: 'Samarium', symbol: 'Sm', group: '-', period: '6', category: 'Lanthanide' },
 63: { name: 'Europium', symbol: 'Eu', group: '-', period: '6', category: 'Lanthanide' },
 64: { name: 'Gadolinium', symbol: 'Gd', group: '-', period: '6', category: 'Lanthanide' },
 65: { name: 'Terbium', symbol: 'Tb', group: '-', period: '6', category: 'Lanthanide' },
 66: { name: 'Dysprosium', symbol: 'Dy', group: '-', period: '6', category: 'Lanthanide' },
 67: { name: 'Holmium', symbol: 'Ho', group: '-', period: '6', category: 'Lanthanide' },
 68: { name: 'Erbium', symbol: 'Er', group: '-', period: '6', category: 'Lanthanide' },
 69: { name: 'Thulium', symbol: 'Tm', group: '-', period: '6', category: 'Lanthanide' },
 70: { name: 'Ytterbium', symbol: 'Yb', group: '-', period: '6', category: 'Lanthanide' },
 71: { name: 'Lutetium', symbol: 'Lu', group: '3', period: '6', category: 'Lanthanide' },
  72: { name: 'Hafnium', symbol: 'Hf', group: '4', period: '6', category: 'Transition Metal' },
 73: { name: 'Tantalum', symbol: 'Ta', group: '5', period: '6', category: 'Transition Metal' },
 74: { name: 'Tungsten', symbol: 'W', group: '6', period: '6', category: 'Transition Metal' },
 75: { name: 'Rhenium', symbol: 'Re', group: '7', period: '6', category: 'Transition Metal' },
 76: { name: 'Osmium', symbol: 'Os', group: '8', period: '6', category: 'Transition Metal' },
 77: { name: 'Iridium', symbol: 'Ir', group: '9', period: '6', category: 'Transition Metal' },
 78: { name: 'Platinum', symbol: 'Pt', group: '10', period: '6', category: 'Transition Metal' },
 79: { name: 'Gold', symbol: 'Au', group: '11', period: '6', category: 'Transition Metal' },
 80: { name: 'Mercury', symbol: 'Hg', group: '12', period: '6', category: 'Transition Metal' },
 81: { name: 'Thallium', symbol: 'Tl', group: '13', period: '6', category: 'Metals' },
 82: { name: 'Lead', symbol: 'Pb', group: '14', period: '6', category: 'Metals' },
 83: { name: 'Bismuth', symbol: 'Bi', group: '15', period: '6', category: 'Metals' },
 84: { name: 'Polonium', symbol: 'Po', group: '16', period: '6', category: 'Metalloids' },
 85: { name: 'Astatine', symbol: 'At', group: '17', period: '6', category: 'Metalloids' },
 86: { name: 'Radon', symbol: 'Rn', group: '18', period: '6', category: 'Noble Gas' },
 87: { name: 'Francium', symbol: 'Fr', group: '1', period: '7', category: 'Alkali Metals' },
 88: { name: 'Radium', symbol: 'Ra', group: '2', period: '7', category: 'Alkaline Earth Metals' },
 89: { name: 'Actinium', symbol: 'Ac', group: '3', period: '7', category: 'Actinide' },
 90: { name: 'Thorium', symbol: 'Th', group: '-', period: '7', category: 'Actinide' },
 91: { name: 'Protactinium', symbol: 'Pa', group: '-', period: '7', category: 'Actinide' },
 92: { name: 'Uranium', symbol: 'U', group: '-', period: '7', category: 'Actinide' },
 93: { name: 'Neptunium', symbol: 'Np', group: '-', period: '7', category: 'Actinide' },
 94: { name: 'Plutonium', symbol: 'Pu', group: '-', period: '7', category: 'Actinide' },
 95: { name: 'Americium', symbol: 'Am', group: '-', period: '7', category: 'Actinide' },
 96: { name: 'Curium', symbol: 'Cm', group: '-', period: '7', category: 'Actinide' },
 97: { name: 'Berkelium', symbol: 'Bk', group: '-', period: '7', category: 'Actinide' },
 98: { name: 'Californium', symbol: 'Cf', group: '-', period: '7', category: 'Actinide' },
 99: { name: 'Einsteinium', symbol: 'Es', group: '-', period: '7', category: 'Actinide' },
100: { name: 'Fermium', symbol: 'Fm', group: '-', period: '7', category: 'Actinide' },
101: { name: 'Mendelevium', symbol: 'Md', group: '-', period: '7', category: 'Actinide' },
102: { name: 'Nobelium', symbol: 'No', group: '-', period: '7', category: 'Actinide' },
103: { name: 'Lawrencium', symbol: 'Lr', group: '3', period: '7', category: 'Actinide' },
104: { name: 'Rutherfordium', symbol: 'Rf', group: '4', period: '7', category: 'Transition Metal' },
105: { name: 'Dubnium', symbol: 'Db', group: '5', period: '7', category: 'Transition Metal' },
106: { name: 'Seaborgium', symbol: 'Sg', group: '6', period: '7', category: 'Transition Metal' },
107: { name: 'Bohrium', symbol: 'Bh', group: '7', period: '7', category: 'Transition Metal' },
108: { name: 'Hassium', symbol: 'Hs', group: '8', period: '7', category: 'Transition Metal' },
109: { name: 'Meitnerium', symbol: 'Mt', group: '9', period: '7', category: 'Metals' },
110: { name: 'Darmstadtium', symbol: 'Ds', group: '10', period: '7', category: 'Metals' },
111: { name: 'Roentgenium', symbol: 'Rg', group: '11', period: '7', category: 'Metals' },
112: { name: 'Copernicium', symbol: 'Cn', group: '12', period: '7', category: 'Transition Metal' },
113: { name: 'Nihonium', symbol: 'Nh', group: '13', period: '7', category: 'Metals' },
114: { name: 'Flerovium', symbol: 'Fl', group: '14', period: '7', category: 'Metals' },
115: { name: 'Moscovium', symbol: 'Mc', group: '15', period: '7', category: 'Metals' },
116: { name: 'Livermorium', symbol: 'Lv', group: '16', period: '7', category: 'Metals' },
117: { name: 'Tennessine', symbol: 'Ts', group: '17', period: '7', category: 'Halogen' },
118: { name: 'Oganesson', symbol: 'Og', group: '18', period: '7', category: 'Noble Gas' }
};
